name: CML Single GPU Test
on: [push]
jobs:
  run:
    runs-on: [self-hosted,cml,gpu]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nvidia-smi
          python -m pip install --upgrade pip
          pip install -e "."
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-pytorch.txt
          pip install -r requirements/requirements-dev.txt
          pytest cleverhans/future/torch/tests